
#
# This is the user-interface definition of a Shiny web application. You can
# run the application by clicking 'Run App' above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

# Define UI for application

######################## Imagem inicial ############################

shinyUI(fluidPage(
  navbarPage(title="Brasileirão 2003-2019", theme = shinytheme("flatly"),
             tabPanel("Inicio",
                      #tabsetPanel(
                        #tabPanel(" ",
                                 fluidRow(
                                   column(12,
                                          img(src = "Brasileirao.jpg", height = 680, width = 1550)#DT::dataTableOutput("table1")
                                          ))#)
                        ##
                        
                        
                        
                      #)# barra de navegacao interna
             ),# barra de navegacao superior (Dados do Participante)
             
             ####################### ABA Tabela ############################
             
             tabPanel("Tabela Brasileirão",
                      tabsetPanel(
                        tabPanel("Tabela Brasileirão de 2003-2019",
                                 fluidRow(
                                   column(12,
                                          DT::dataTableOutput("table1")
                                   )))
                        ##
                        
                        
                        
                      )# barra de navegacao interna
             ),# barra de navegacao superior (Dados do Participante)
             
             ####################### ABA ARENA ############################
             
             tabPanel("Arenas",
                      tabsetPanel(
                        ##
                        tabPanel("Jogos por Arena",
                                 fluidRow(column(3, 
                                                 selectInput("Ano1", 
                                                             strong("Selecione o ano:"), 
                                                             choices=c("2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019"),
                                                             selected = "2019")),
                                          column(9,
                                                 plotlyOutput("plot21", height = 600)))),
                        
                        tabPanel("Arenas com mais jogos",
                                 fluidRow(column(9,
                                                 plotlyOutput("plot1", height = 600)))),
                        tabPanel("Arenas com menos jogos",
                                 fluidRow(column(9,
                                                 plotlyOutput("plot2", height = 600))))
                        
                      )# barra de navegacao interna
             ),# barra de navegacao superior (Dados da Escola)
             
             ######################## ABA PONTOS ############################
           
             tabPanel("Pontuação",
                      tabsetPanel(
                        ##
                       tabPanel("Pontuação final",
                                fluidRow(column(3, 
                                                selectInput("Ano53", 
                                                            strong("Selecione o ano:"), 
                                                            choices=c("Todos os anos"= "Todos os anos",
                                                                      "2003"="2003",
                                                                      "2004"="2004",
                                                                      "2005"="2005",
                                                                      "2006"="2006",
                                                                      "2007"="2007",
                                                                      "2008"="2008",
                                                                      "2009"="2009",
                                                                      "2010"="2010",
                                                                      "2011"="2011",
                                                                      "2012"="2012",
                                                                      "2013"="2013",
                                                                      "2014"="2014",
                                                                      "2015"="2015",
                                                                      "2016"="2016",
                                                                      "2017"="2017",
                                                                      "2018"="2018",
                                                                      "2019"="2019"),
                                                            selected = "2019")),
                                         column(9,
                                                plotlyOutput("plot5", height = 600),
                                                tableOutput("tabAno53")))),
                        tabPanel("Pontuação como Mandante",
                                 fluidRow(column(3, 
                                                 selectInput("Ano51", 
                                                             strong("Selecione o ano:"), 
                                                             choices=c("Todos os anos"= "Todos os anos",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019"),
                                                             selected = "2019")),
                                          column(9,
                                                 plotlyOutput("plot3", height = 600)))),
                       
                        tabPanel("Pontuação como Visitante",
                                 fluidRow(column(3, 
                                                 selectInput("Ano52", 
                                                             strong("Selecione o ano:"), 
                                                             choices=c("Todos os anos"= "Todos os anos",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019"),
                                                             selected = "2019")),
                                          column(9,
                                                 plotlyOutput("plot4", height = 600)))),
                       tabPanel("Campeões",
                                fluidRow(column(3, 
                                                selectInput("Ano99", 
                                                            strong("Selecione o ano:"), 
                                                            choices=c("2003"="2003",
                                                                      "2004"="2004",
                                                                      "2005"="2005",
                                                                      "2006"="2006",
                                                                      "2007"="2007",
                                                                      "2008"="2008",
                                                                      "2009"="2009",
                                                                      "2010"="2010",
                                                                      "2011"="2011",
                                                                      "2012"="2012",
                                                                      "2013"="2013",
                                                                      "2014"="2014",
                                                                      "2015"="2015",
                                                                      "2016"="2016",
                                                                      "2017"="2017",
                                                                      "2018"="2018",
                                                                      "2019"="2019"),
                                                            selected = "2019")),
                                         column(9,
                                                plotlyOutput("plot99", height = 600)))),
                       tabPanel("Rebaixados",
                                fluidRow(column(3, 
                                                selectInput("Ano98", 
                                                            strong("Selecione o ano:"), 
                                                            choices=c("2003"="2003",
                                                                      "2004"="2004",
                                                                      "2005"="2005",
                                                                      "2006"="2006",
                                                                      "2007"="2007",
                                                                      "2008"="2008",
                                                                      "2009"="2009",
                                                                      "2010"="2010",
                                                                      "2011"="2011",
                                                                      "2012"="2012",
                                                                      "2013"="2013",
                                                                      "2014"="2014",
                                                                      "2015"="2015",
                                                                      "2016"="2016",
                                                                      "2017"="2017",
                                                                      "2018"="2018",
                                                                      "2019"="2019"),
                                                            selected = "2019")),
                                         column(9,
                                                plotlyOutput("plot98", height = 600))))
                        
                      )# barra de navegacao interna
             ),# barra de navegacao superior (Dados da Escola)  
             
             ######################## ABA VITORIAS ############################
             
             tabPanel("Vitórias",
                      tabsetPanel(
                        ##
                        tabPanel("Vitórias por ano",
                                 fluidRow(column(3, 
                                                 selectInput("Ano2", 
                                                             strong("Selecione o ano:"), 
                                                             choices=c("Todos os anos"= "Todos os anos",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019"),
                                                             selected = "2019")),
                                          column(9,
                                                 plotlyOutput("plot22", height = 600)))),
                        tabPanel("Vitórias como Mandante",
                                 fluidRow(column(3, 
                                                 selectInput("Ano22", 
                                                             strong("Selecione o ano:"), 
                                                             choices=c("Todos os anos"= "Todos os anos",
                                                               "2003"="2003",
                                                               "2004"="2004",
                                                               "2005"="2005",
                                                               "2006"="2006",
                                                               "2007"="2007",
                                                               "2008"="2008",
                                                               "2009"="2009",
                                                               "2010"="2010",
                                                               "2011"="2011",
                                                               "2012"="2012",
                                                               "2013"="2013",
                                                               "2014"="2014",
                                                               "2015"="2015",
                                                               "2016"="2016",
                                                               "2017"="2017",
                                                               "2018"="2018",
                                                               "2019"="2019"),
                                                             selected = "2019")),
                                          column(9,
                                                 plotlyOutput("plot6", height = 600)))),
                        
                                     tabPanel("Vitórias como Visitante",
                                 fluidRow(column(3, 
                                                 selectInput("Ano42", 
                                                             strong("Selecione o ano:"), 
                                                             choices=c("Todos os anos"= "Todos os anos",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019"),
                                                             selected = "2019")),
                                          column(9,
                                                 plotlyOutput("plot7", height = 600))))
                       
                        
                      )# barra de navegacao interna
             ),# barra de navegacao superior (Dados da Escola)  
             
             ######################## ABA EMPATES ############################
             
             tabPanel("Empates",
                      tabsetPanel(
                        ##
                        tabPanel("Empates por ano",
                                       fluidRow(column(3, 
                                                      selectInput("Ano91", 
                                                                      strong("Selecione o ano:"), 
                                                                      choices=c("Todos os anos"= "Todos os anos",
                                                                                "2003"="2003",
                                                                                "2004"="2004",
                                                                                "2005"="2005",
                                                                                "2006"="2006",
                                                                                "2007"="2007",
                                                                                "2008"="2008",
                                                                                "2009"="2009",
                                                                                "2010"="2010",
                                                                                "2011"="2011",
                                                                                "2012"="2012",
                                                                                "2013"="2013",
                                                                                "2014"="2014",
                                                                                "2015"="2015",
                                                                                "2016"="2016",
                                                                                "2017"="2017",
                                                                                "2018"="2018",
                                                                                "2019"="2019"),
                                                                      selected = "2019")),
                                                   column(9,
                                                          plotlyOutput("plot9", height = 600)))),
                        tabPanel("Empates como Mandante",
                                                  fluidRow(column(3, 
                                                          selectInput("Ano92", 
                                                                      strong("Selecione o ano:"), 
                                                                      choices=c("Todos os anos"= "Todos os anos",
                                                                                "2003"="2003",
                                                                                "2004"="2004",
                                                                                "2005"="2005",
                                                                                "2006"="2006",
                                                                                "2007"="2007",
                                                                                "2008"="2008",
                                                                                "2009"="2009",
                                                                                "2010"="2010",
                                                                                "2011"="2011",
                                                                                "2012"="2012",
                                                                                "2013"="2013",
                                                                                "2014"="2014",
                                                                                "2015"="2015",
                                                                                "2016"="2016",
                                                                                "2017"="2017",
                                                                                "2018"="2018",
                                                                                "2019"="2019"),
                                                                      selected = "2019")),
                                                   column(9,
                                                          plotlyOutput("plot10", height = 600)))),
                                                   tabPanel("Empates como Visitante",
                                                   fluidRow(column(3, 
                                                             selectInput("Ano93", 
                                                                                      strong("Selecione o ano:"), 
                                                                                      choices=c("Todos os anos"= "Todos os anos",
                                                                                                "2003"="2003",
                                                                                                "2004"="2004",
                                                                                                "2005"="2005",
                                                                                                "2006"="2006",
                                                                                                "2007"="2007",
                                                                                                "2008"="2008",
                                                                                                "2009"="2009",
                                                                                                "2010"="2010",
                                                                                                "2011"="2011",
                                                                                                "2012"="2012",
                                                                                                "2013"="2013",
                                                                                                "2014"="2014",
                                                                                                "2015"="2015",
                                                                                                "2016"="2016",
                                                                                                "2017"="2017",
                                                                                                "2018"="2018",
                                                                                                "2019"="2019"),
                                                                                      selected = "2019")),
                                                                   column(9,
                                                                          plotlyOutput("plot11", height = 600))))
                        
                        
                      )# barra de navegacao interna
             ),# barra de navegacao superior (Dados da Escola)  
             
             ######################## ABA DERROTAS ############################
             
             tabPanel("Derrotas",
                      tabsetPanel(
                        ##
                        tabPanel("Derrotas por ano",
                                 fluidRow(column(3, 
                                                 selectInput("Ano3", 
                                                             strong("Selecione o ano:"), 
                                                             choices=c("Todos os anos"= "Todos os anos",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019"),
                                                             selected = "2019")),
                                          column(9,
                                                 plotlyOutput("plot23", height = 600)))),
                        tabPanel("Derrotas como Mandante",
                                 fluidRow(column(3,
                                                 selectInput("Ano95", 
                                                             strong("Selecione o ano:"), 
                                                             choices=c("Todos os anos"= "Todos os anos",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019"),
                                                             selected = "2019")),
                                          column(9,
                                                 plotlyOutput("plot13", height = 600)))),
                        tabPanel("Derrotas como Visitante",
                                 fluidRow(column(3,
                                                 selectInput("Ano94", 
                                                             strong("Selecione o ano:"), 
                                                             choices=c("Todos os anos"= "Todos os anos",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019"),
                                                             selected = "2019")),
                                          column(9,
                                                 plotlyOutput("plot14", height = 600))))
                      
                        
                      )# barra de navegacao interna
             ),# barra de navegacao superior (Dados da Escola)  
             
             ######################## ABA GOLS ############################
             
             tabPanel("Gols por equipes",
                      tabsetPanel(
                        ##
                        tabPanel("Gols por ano",
                                 fluidRow(column(3, 
                                                 selectInput("Ano59", 
                                                             strong("Selecione o ano:"), 
                                                             choices=c("Todos os anos"= "Todos os anos",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019"),
                                                             selected = "2019")),
                                          column(9,
                                                 plotlyOutput("plot59", height = 600)))),
                        tabPanel("Gols como Mandante",
                                 fluidRow(column(3, 
                                                 selectInput("Ano84", 
                                                             strong("Selecione o ano:"), 
                                                             choices=c("Todos os anos"= "Todos os anos",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019"),
                                                             selected = "2019")),
                                          column(9,
                                                 plotlyOutput("plot16", height = 600)))),
                        tabPanel("Gols como Visitante",
                                 fluidRow(column(3, 
                                                 selectInput("Ano85", 
                                                             strong("Selecione o ano:"), 
                                                             choices=c("Todos os anos"= "Todos os anos",
                                                                       "2003"="2003",
                                                                       "2004"="2004",
                                                                       "2005"="2005",
                                                                       "2006"="2006",
                                                                       "2007"="2007",
                                                                       "2008"="2008",
                                                                       "2009"="2009",
                                                                       "2010"="2010",
                                                                       "2011"="2011",
                                                                       "2012"="2012",
                                                                       "2013"="2013",
                                                                       "2014"="2014",
                                                                       "2015"="2015",
                                                                       "2016"="2016",
                                                                       "2017"="2017",
                                                                       "2018"="2018",
                                                                       "2019"="2019"),
                                                             selected = "2019")),
                                          column(9,
                                                 plotlyOutput("plot17", height = 600))))
                        
                        
                      )# barra de navegacao interna
             ),# barra de navegacao superior (Dados da Escola)            
             
             ######################## ABA JOGOS ############################
             
             tabPanel("Números de jogos",
                      tabsetPanel(
                        ##
                        tabPanel("Jogos disputados",
                                 fluidRow(column(9,
                                                 plotlyOutput("plot18", height = 600)))),
                        tabPanel("Jogos como Mandante",
                                 fluidRow(column(9,
                                                 plotlyOutput("plot19", height = 600)))),
                        tabPanel("Jogos como Visitante",
                                 fluidRow(column(9,
                                                 plotlyOutput("plot20", height = 600))))
                                
                        
                        
                      )# barra de navegacao interna
             ),# barra de navegacao superior (Dados da Escola)  
           
          
                        tabPanel("Confrontos",
                                 tabsetPanel(
                                   ##
                                   tabPanel("Equipes",
                                            fluidRow(column(3, 
                                                            selectInput("TIME123", 
                                                                        strong("Selecione o Mandante:"), 
                                                                        choices=c("AMERICA-MG",
                                                                                  "AMERICA-RN",
                                                                                  "ATHLETICO-PR",
                                                                                  "ATLETICO-GO",
                                                                                  "ATLETICO-MG",
                                                                                  "AVAI",
                                                                                  "BAHIA",
                                                                                  "BARUERI",
                                                                                  "BOTAFOGO-RJ",
                                                                                  "BRASILIENSE",
                                                                                  "CEARA",
                                                                                  "CHAPECOENSE",
                                                                                  "CORINTHIANS",
                                                                                  "CORITIBA",
                                                                                  "CRICIUMA",
                                                                                  "CRUZEIRO",
                                                                                  "CSA",
                                                                                  "FIGUEIRENSE",
                                                                                  "FLAMENGO",
                                                                                  "FLUMINENSE",
                                                                                  "FORTALEZA",
                                                                                  "GOIAS",
                                                                                  "GREMIO",
                                                                                  "GREMIO PRUDENTE",
                                                                                  "GUARANI",
                                                                                  "INTERNACIONAL",
                                                                                  "IPATINGA",
                                                                                  "JOINVILLE",
                                                                                  "JUVENTUDE",
                                                                                  "NAUTICO",
                                                                                  "PALMEIRAS",
                                                                                  "PARANA",
                                                                                  "PAYSANDU",
                                                                                  "PONTE PRETA",
                                                                                  "PORTUGUESA",
                                                                                  "SANTA CRUZ",
                                                                                  "SANTO ANDRE",
                                                                                  "SANTOS",
                                                                                  "SAO CAETANO",
                                                                                  "SAO PAULO",
                                                                                  "SPORT",
                                                                                  "VASCO",
                                                                                  "VITORIA"
                                                                                  
                                                                        ),
                                                                        selected = "FLAMENGO"),
                                                     
                                                     selectInput("TIME124", 
                                                                 strong("Selecione o Visitante:"), 
                                                                 choices=c(
                                                                   "AMERICA-MG",
                                                                   "AMERICA-RN",
                                                                   "ATHLETICO-PR",
                                                                   "ATLETICO-GO",
                                                                   "ATLETICO-MG",
                                                                   "AVAI",
                                                                   "BAHIA",
                                                                   "BARUERI",
                                                                   "BOTAFOGO-RJ",
                                                                   "BRASILIENSE",
                                                                   "CEARA",
                                                                   "CHAPECOENSE",
                                                                   "CORINTHIANS",
                                                                   "CORITIBA",
                                                                   "CRICIUMA",
                                                                   "CRUZEIRO",
                                                                   "CSA",
                                                                   "FIGUEIRENSE",
                                                                   "FLAMENGO",
                                                                   "FLUMINENSE",
                                                                   "FORTALEZA",
                                                                   "GOIAS",
                                                                   "GREMIO",
                                                                   "GREMIO PRUDENTE",
                                                                   "GUARANI",
                                                                   "INTERNACIONAL",
                                                                   "IPATINGA",
                                                                   "JOINVILLE",
                                                                   "JUVENTUDE",
                                                                   "NAUTICO",
                                                                   "PALMEIRAS",
                                                                   "PARANA",
                                                                   "PAYSANDU",
                                                                   "PONTE PRETA",
                                                                   "PORTUGUESA",
                                                                   "SANTA CRUZ",
                                                                   "SANTO ANDRE",
                                                                   "SANTOS",
                                                                   "SAO CAETANO",
                                                                   "SAO PAULO",
                                                                   "SPORT",
                                                                   "VASCO",
                                                                   "VITORIA"
                                                                 ),
                                                                 selected = "CRUZEIRO")),
                                            
<<<<<<< HEAD
                                            column(9,
                                                   DT::dataTableOutput("tab122"))))
=======
                                            column(9, DT::dataTableOutput("tab122"))))
>>>>>>> 70ede7fdd1ec910c79eed7db96cf6f33f0fb9813
 
            
                        
                        
                        
                        
                      )# barra de navegacao interna
             ),# barra de navegacao superior (Dados da Escola)  
             
             
                       tabPanel("Sobre", icon = icon("comment", lib = "glyphicon"),
                      includeMarkdown("sobre.md"))
                    
    )#navbarPage
)#fluidPage
)#shinyUI
